image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: 3.0.5-arm64        # swap to -arm64-64k if jemalloc crash

service:
  type: ClusterIP
  ports:
    - name: http
      port: 2020
      targetPort: 2020

config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  inputs: |
    [INPUT]
        Name   dummy
        Dummy  {"message":"fluent-bit is alive"}

  outputs: |
    [OUTPUT]
        Name   stdout
        Match  *

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

#  Add this block at the bottom of the same file
readinessProbe:
  httpGet:
    path: /api/v1/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 6

livenessProbe:
  httpGet:
    path: /api/v1/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 6
