service:
  type: ClusterIP
  ports:
    - name: http
      port: 2020
      targetPort: 2020

config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  inputs: |
    [INPUT]
        Name   dummy
        Dummy  {"message":"fluent-bit is alive"}

  outputs: |
    [OUTPUT]
        Name   stdout
        Match  *

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
