image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: arm64-64k                            # <-- tag you push
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 2020
      targetPort: 2020

config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*

  outputs: |
    [OUTPUT]
        Name              syslog
        Match             kube.*
        Host              syslog-ng.logging.svc.cluster.local
        Port              514
        Mode              udp
        Syslog_Format     rfc5424
