apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day1-foundation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"   # ensure this waits until Day-0 apps are healthy
spec:
  project: default
  source:
    repoURL: https://github.com/gorttman/day1-foundation.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
