apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secrets-app.yml
  - sealed-secrets-backup-rbac.yml
  - sealed-secrets-backup-cron.yml
  - sealed-secrets-backup-pvc.yml
