apiVersion: batch/v1
kind: CronJob
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
spec:
  schedule: "0 1 * * *"   # daily at 01:00
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: bitnami/kubectl:1.32
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  echo "[*] Daily sealed-secrets backup..."
                  KEY="$(kubectl -n kube-system get secret -l sealedsecrets.bitnami.com/sealed-secrets-key=active -o name | head -n1)"
                  if [ -z "$KEY" ]; then
                    echo "No active sealed-secrets key found"; exit 0
                  fi
                  kubectl -n kube-system get "$KEY" -o yaml \
                    > /mnt/backup/${KEY##*/}-$(date +%F-%H%M).yaml
                  echo "[*] Backup complete."
              volumeMounts:
                - name: backup-storage
                  mountPath: /mnt/backup
          volumes:
            - name: backup-storage
              hostPath:
                path: /mnt/backup
                type: DirectoryOrCreate
