# apps/sealed-secrets/sealed-secrets-backup-cron.yml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  schedule: "0 1 * * *"         # run daily at 01:00
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          serviceAccountName: sealed-secrets-backup
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: bitnami/kubectl:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  echo "[*] Starting sealed-secrets backup job..."
                  KEY="$(kubectl -n kube-system get secret -l sealedsecrets.bitnami.com/sealed-secrets-key=active -o name | head -n1)"
                  if [ -z "$KEY" ]; then
                    echo "[!] No active sealed-secrets key found"
                    exit 0
                  fi
                  OUT="/mnt/backup/${KEY##*/}-$(date +%F-%H%M).yaml"
                  kubectl -n kube-system get "$KEY" -o yaml > "$OUT"
                  echo "[*] Backup written to $OUT"
              volumeMounts:
                - name: backup-storage
                  mountPath: /mnt/backup
          volumes:
            - name: backup-storage
              hostPath:
                path: /mnt/backup
                type: DirectoryOrCreate
