apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
    # 1. The actual chart
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.16.1
      helm:
        valueFiles:
          - $values/apps/sealed-secrets/sealed-secrets-values.yml

    # 2. Your repo containing the values file
    - repoURL: https://github.com/gorttman/day0-bootstrap.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
