apiVersion: batch/v1
kind: CronJob
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
spec:
  schedule: "0 3 * * 0"   # every Sunday at 03:00
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: bitnami/kubectl:1.30
            command:
              - /bin/sh
              - -c
              - |
                set -e
                KEY=$(kubectl -n kube-system get secret -l sealedsecrets.bitnami.com/sealed-secrets-key=active -o name | head -n1)
                if [ -n "$KEY" ]; then
                  kubectl -n kube-system get "$KEY" -o yaml > /backups/${KEY##*/}-$(date +%F-%H%M%S).yaml
                else
                  echo "No active sealed-secrets key found"
                fi
            volumeMounts:
              - name: backup
                mountPath: /backups
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: sealed-secrets-backup-pvc
