apiVersion: batch/v1
kind: CronJob
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  schedule: "*/10 * * * *"   # every 10 minutes for testing (switch back later)
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            job-name: sealed-secrets-backup
        spec:
          serviceAccountName: sealed-secrets-backup
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: ghcr.io/bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  echo "[*] Daily sealed-secrets backup..."
                  KEY="$(kubectl -n kube-system get secret -l sealedsecrets.bitnami.com/sealed-secrets-key=active -o name | head -n1)"
                  if [ -z "$KEY" ]; then
                    echo "No active sealed-secrets key found"; exit 0
                  fi
                  kubectl -n kube-system get "$KEY" -o yaml \
                    > /mnt/backup/${KEY##*/}-$(date +%F-%H%M).yaml
                  echo "[*] Backup complete."
              volumeMounts:
                - name: backup-storage
                  mountPath: /mnt/backup
          volumes:
            - name: backup-storage
              hostPath:
                path: /mnt/backup
                type: DirectoryOrCreate
