apiVersion: batch/v1
kind: Job
metadata:
  name: sealed-secrets-backup-bootstrap
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: sealed-secrets-backup
      restartPolicy: OnFailure
      containers:
        - name: backup
          image: quay.io/bitnami/kubectl:1.32
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "[*] Bootstrap sealed-secrets backup..."
              KEY="$(kubectl -n kube-system get secret -l sealedsecrets.bitnami.com/sealed-secrets-key=active -o name | head -n1)"
              if [ -z "$KEY" ]; then
                echo "No active sealed-secrets key found"; exit 0
              fi
              kubectl -n kube-system get "$KEY" -o yaml \
                > /mnt/backup/${KEY##*/}-bootstrap-$(date +%F-%H%M).yaml
              echo "[*] Bootstrap backup complete."
          volumeMounts:
            - name: backup-storage
              mountPath: /mnt/backup
      volumes:
        - name: backup-storage
          hostPath:
            path: /mnt/backup
            type: DirectoryOrCreate
