apiVersion: batch/v1
kind: Job
metadata:
  name: sealed-secrets-backup-bootstrap
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: backup
          image: bitnami/kubectl:1.32
          command:
            - /bin/sh
            - -c
            - |
              echo "[*] One-time bootstrap backup..."
              kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key=active -o yaml > /backup/sealed-secrets-key-bootstrap.yaml
          volumeMounts:
            - name: backup-storage
              mountPath: /mnt/backup
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: sealed-secrets-backup-pvc
