# apps/sealed-secrets/sealed-secrets-app.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    # Official Bitnami Sealed Secrets controller manifest (v0.27.0)
    repoURL: https://github.com/bitnami-labs/sealed-secrets
    targetRevision: v0.27.0
    path: "helm/sealed-secrets/crds/../.."
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
