# apps/sealed-secrets/sealed-secrets-backup-rbac.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-backup
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-backup
subjects:
  - kind: ServiceAccount
    name: sealed-secrets-backup
    namespace: kube-system
