apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sealed-secrets-backup-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path   # works with k3s default; change if you use NFS later
