# day1-foundation/apps/values/ingress-nginx-values.yml

controller:
  replicaCount: 1

  service:
    type: NodePort   # or LoadBalancer if you have cloud/MetalLB
    nodePorts:
      http: 31080
      https: 31443

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

  admissionWebhooks:
    enabled: true

defaultBackend:
  enabled: true
