apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp-server
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcp-server
  template:
    metadata:
      labels:
        app: dhcp-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: dhcp-server
          image: networkboot/dhcpd:latest
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              cp /config/dhcpd.conf /data/dhcpd.conf
              touch /data/dhcpd.leases
              exec /usr/sbin/dhcpd -f -d \
                -cf /data/dhcpd.conf \
                -lf /data/dhcpd.leases \
                eth0
          volumeMounts:
            - name: dhcpd-config
              mountPath: /config
            - name: dhcpd-data
              mountPath: /data
      volumes:
        - name: dhcpd-config
          configMap:
            name: dhcpd-config
        - name: dhcpd-data
          emptyDir: {}   # or hostPath if you want leases to persist
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dhcpd-config
  namespace: infra
data:
  dhcpd.conf: |
    default-lease-time 600;
    max-lease-time 7200;
    authoritative;

    subnet 192.168.1.0 netmask 255.255.255.0 {
      range 192.168.1.100 192.168.1.200;
      option routers 192.168.1.1;
      option domain-name-servers 192.168.1.1;
      filename "pxelinux.0";
      next-server 192.168.1.10;
    }
