apiVersion: apps/v1
kind: Deployment
metadata:
  name: tftp-server
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tftp
  template:
    metadata:
      labels:
        app: tftp
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: tftp
        image: 3x3cut0r/tftpd-hpa
        args: ["-L", "--verbose", "-s", "/srv/tftp"]
        volumeMounts:
        - name: tftp-data
          mountPath: /srv/tftp
      volumes:
      - name: tftp-data
        hostPath:
          path: /srv/tftp
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: tftp
  namespace: infra
spec:
  type: ClusterIP
  selector:
    app: tftp
  ports:
  - name: tftp
    port: 69
    protocol: UDP
    targetPort: 69
