apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day1-foundation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gorttman/day1-foundation.git
    targetRevision: main
    path: apps
#    directory: 
#      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
