apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day2-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gorttman/day2-services.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
