apiVersion: v1
kind: Namespace
metadata:
  name: infra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner
      chart: nfs-server-provisioner
      targetRevision: 1.8.0
      helm:
        releaseName: nfs-server
        valueFiles:
          - $values/apps/values/nfs-server-values.yml
    - repoURL: https://github.com/gorttman/day0-bootstrap.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
